# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 981798a5a21cefc898511189924d171dcef6bc49e7690fe9ba3b016b187f0d81322d8f82685481f65e7d854c246f53b119ac1b2ed2a963e0a0f2697ba679b6f0

test:
  secret_key_base: 79bae987bdb8987963d0d9fdd5aea1a8c8aea10c8f173d764ba118fb5aafbbaec249c3a3e62778b377ac27196c4a209e562be1c1927eba0a1109aa9ea0976b26

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
